# Generated by Django 2.1.3 on 2018-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_user', models.CharField(max_length=50)),
                ('log_detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Docker_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='dockerAPI端口')),
                ('apiversion', models.CharField(blank=True, default='1.21', max_length=50, verbose_name='API版本')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='docker用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='docker密码')),
            ],
        ),
        migrations.CreateModel(
            name='Jenkins_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='jenkins端口')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='jenkins用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='jenkins密码')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='supervisorRPC端口')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='supervisor用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='supervisor密码')),
            ],
        ),
    ]
