# Generated by Django 2.1.3 on 2018-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181206_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_superuser',
            field=models.BooleanField(default=1, verbose_name='是否超级用户'),
            preserve_default=False,
        ),
    ]
