# Generated by Django 2.1.3 on 2018-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_info_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='描述'),
        ),
    ]
