# Generated by Django 2.1.3 on 2018-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
    ]
