# Generated by Django 2.1.3 on 2018-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181206_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_server',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='jenkins_server',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='supervisor_server',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='描述'),
        ),
    ]
