# Generated by Django 2.1.3 on 2018-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supervisor_server_apiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkins_server',
            name='apiversion',
            field=models.CharField(blank=True, default='1.21', max_length=50, verbose_name='API版本'),
        ),
    ]
