# Generated by Django 2.1.3 on 2018-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181211_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='ssh端口')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='ssh用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='ssh密码')),
                ('description', models.CharField(blank=True, default='', max_length=128, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(max_length=50, unique=True, verbose_name='主机类型')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.ManyToManyField(to='app.ServerType'),
        ),
    ]
