# Generated by Django 2.1.3 on 2019-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181220_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=50, unique=True, verbose_name='hostname')),
                ('host_port', models.GenericIPAddressField(verbose_name='server ip')),
                ('host_username', models.CharField(max_length=50)),
                ('host_password', models.CharField(max_length=50)),
                ('container_id', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=50)),
                ('statename', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Docker_Server',
        ),
        migrations.DeleteModel(
            name='Supervisor_Server',
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=50, unique=True, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='server ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ssh password'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(verbose_name='ssh port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ssh username'),
        ),
        migrations.AlterField(
            model_name='servertype',
            name='server_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='server type'),
        ),
    ]
