# Generated by Django 2.1.3 on 2019-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190426_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermodel',
            name='host_ip',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='containermodel',
            name='host_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='containermodel',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='containermodel',
            name='port',
            field=models.CharField(max_length=256),
        ),
    ]
