# Generated by Django 2.1.3 on 2019-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190426_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerInfo',
            fields=[
                ('container_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host_ip', models.CharField()),
                ('host_port', models.IntegerField()),
                ('host_username', models.CharField(max_length=128)),
                ('host_password', models.CharField(max_length=128)),
                ('container_id', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=128)),
                ('created', models.CharField(max_length=128)),
                ('statename', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('port', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('current_user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'app_container_info',
                'ordering': ['container_info_id'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='邮箱')),
                ('is_superuser', models.BooleanField(verbose_name='是否超级用户')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
            ],
            options={
                'db_table': 'app_user_info',
                'ordering': ['user_id'],
            },
        ),
        migrations.RenameModel(
            old_name='Action_Log',
            new_name='ActionLog',
        ),
        migrations.DeleteModel(
            name='ContainerModel',
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='actionlog',
            table='app_action_log',
        ),
    ]
