# Generated by Django 2.1.3 on 2018-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0002_auto_20181112_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.ManyToManyField(blank=True, to='mmanager_app.Server_Type'),
        ),
    ]
