# Generated by Django 2.1.3 on 2018-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0003_auto_20181113_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_type',
            name='name',
            field=models.CharField(max_length=100, verbose_name='主机类型'),
        ),
    ]
