# Generated by Django 2.1.3 on 2018-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0004_auto_20181113_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password_supervisor',
            field=models.CharField(default='', max_length=50, verbose_name='supervisor密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='user_supervisor',
            field=models.CharField(default='', max_length=50, verbose_name='supervisor用户名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.ManyToManyField(blank=True, to='mmanager_app.Server_Type', verbose_name='主机类型'),
        ),
    ]
