# Generated by Django 2.1.3 on 2018-11-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0005_auto_20181113_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='password_supervisor',
        ),
        migrations.RemoveField(
            model_name='server',
            name='user_supervisor',
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='supervisor密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='supervisor用户名'),
        ),
    ]
