# Generated by Django 2.1.3 on 2018-11-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0006_auto_20181114_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='Supervisor_Server',
        ),
    ]
