# Generated by Django 2.1.3 on 2018-11-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0007_auto_20181114_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='dockerAPI端口')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='docker用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='docker密码')),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor_server',
            name='server_type',
        ),
        migrations.AlterField(
            model_name='supervisor_server',
            name='port',
            field=models.IntegerField(verbose_name='supervisor端口'),
        ),
        migrations.DeleteModel(
            name='Server_Type',
        ),
    ]
