# Generated by Django 2.1.3 on 2018-11-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0008_auto_20181114_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateField(auto_now_add=True)),
                ('log_user', models.CharField(max_length=50)),
                ('log_detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='supervisor_server',
            name='port',
            field=models.IntegerField(verbose_name='supervisorRPC端口'),
        ),
    ]
