# Generated by Django 2.1.3 on 2018-11-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0009_auto_20181119_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
