# Generated by Django 2.1.3 on 2018-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0010_auto_20181119_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_server',
            name='apiversion',
            field=models.CharField(blank=True, default='1.21', max_length=50, verbose_name='API版本'),
        ),
    ]
