# Generated by Django 2.1.3 on 2018-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmanager_app', '0011_docker_server_apiversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenkins_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='jenkins端口')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='jenkins用户名')),
                ('password', models.CharField(blank=True, default='', max_length=50, verbose_name='jenkins密码')),
            ],
        ),
    ]
